name: Run unit tests for API and CLIENT

# Sets the events which will trigger the Action
# `push` = any "push" action to the GitHub "remote",
# changes to any branch will be considered
on: [push, pull_request, release]

jobs:
  # `build` is a user-defined name for this job
  build:
    # Set the base environment to run the Action on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps to complete the job
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      - run: npm test:unit
      # - run: npm run build --if-present
